import Head from 'next/head'
import {useRouter} from "next/router"
import PageHeader from '@/components/PageHeader'

export default function Login() {
    const router = useRouter()

    function signupLink() {
        router.push('/signup')
    }

  return (
    <div className=''>
      <Head>
        <title>Dashboard | Bear-ly Breaking Even</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport"/>
        <link rel="icon" />
      </Head>

      <PageHeader/>

      <div className=' px-3 pt-10'>
        <div className=' flex grid rounded-lg  mx-auto h-max  bg-[#f2eadf] pb-2 pt-4 border border-black space'>
          <div className=' flex mx-6 my-5  text-xl font-semibold'>
              Welcome -insert username here-!
          </div>
          <div className='flex px-4 py-1'>
            <div>Insert Income:</div>
            <input className="shadow appearance-none border rounded mx-2 py-1 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="income" type="number" placeholder="ex. 125000"></input>
            <button className=' text-sm hover:cursor-pointer bg-[#addfad] drop-shadow-lg rounded-lg px-3 py-1 border border-black'> Submit </button>
          </div>
        </div>
        <div className=' flex mx-5 my-5 text-gray-500 text-sm font-semibold'> Copyright © 2023 SMD Inc. </div>
      </div>
    </div>
  )
}