import Head from 'next/head'
import styles from '@/styles/Home.module.css'


export default function Home() {
  return (
    <div className='bg-pink-400'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </div>
  )
}
