import Head from 'next/head'
import styles from '@/styles/Home.module.css'


export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex w-screen h-screen items-center justify-center'>
        <div className='bg-[#addfad] pl-5 pr-5 pt-2 pb-2 border'>
        <button className=''>Login</button>
        </div>
      </div>
    </div>
  )
}
