import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {useRouter} from "next/router"

var users: string[] = []
var userObjects: object[] = []

export default function SignUp() {
    
  const router = useRouter()
  
  function logLink(){
      router.push('/login')
  }

    function storeUsername() {
      // get username, password, and confirm password input fields
      var username = document.getElementById('nU')
      var password = document.getElementById('nP')
      var confirmPassword = document.getElementById('cP')
      
      // create user obeject
      const user: object = {
        name: username.value,
        password: password.value
      }

      // check if username field isnt empty and username doesnt already exist
      if (!(username.value == '' || users.includes(username.value))) {
        // check if password field and confirm password field are not empty and are equal
        if (!(password.value == '' || confirmPassword.value == '') && password.value == confirmPassword.value) {
          users.push(user.name)
          userObjects.push(user)
        }
      }
      // reset username, password and confirm password fields
      username.value = ''
      password.value = ''
      confirmPassword.value = ''

      console.log(userObjects.length)
      console.log(users.length)
    }
<<<<<<< HEAD
    
=======

>>>>>>> c1daa6f822fe2c886d0f79e613a7fe46dcc40cfb
  return (
    <div className=''>
      <Head>
        <title>Bear-ly Breaking Even Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex items-center justify-center space-y-6'>
        <div>

        </div>
        <div className='grid flex rounded-lg px-16 mx-auto h-fit justify-center bg-[#f2eadf] pb-2 pt-4 border border-black space'>
          <div className='mx-auto justify-center text-xl font-semibold'>
              Create an Account
          </div>
          <div className='flex pt-4 pb-1'>
            <div>New Username</div>
          </div>
          <input className="shadow appearance-none border rounded w-full py-2.5 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="nU" type="text" placeholder="Username"></input>
          <div className='flex pt-4 pb-1'>
            <div>New Password</div>
          </div>
          <input className="shadow appearance-none border rounded w-full py-2.5 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="nP" type="password" placeholder="********"></input>
          <div className='flex pt-4 pb-1'>
            <div>Confirm Password</div>
          </div>
          <input className="shadow appearance-none border rounded w-full py-2.5 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" id="cP" type="password" placeholder="********"></input>
          
          <div className='mx-auto pb-2 pt-3'>
            <button onClick={storeUsername} className='bg-[#addfad] drop-shadow-lg rounded-lg px-6 py-3 border border-black'>
              <div className='font-semibold'>
                Sign Up
              </div>
            </button>
          </div>
          <div className='flex text-gray-600 text-sm py-2'>
            <div>Already have an account? &nbsp;</div>
        <button onClick={logLink} className='underline hover:cursor-pointer'> Log in </button>
          </div>
        </div>
      </div>
    </div>
  )
}